---
version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: httpbin
          ContainerPort: 80
        PlatformVersion: LATEST
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - subnet-09a3c0d1291faa569
              - subnet-0b6215a285eaba936
              - subnet-06f8b3e430c022e12
            SecurityGroups:
              - sg-0544a6b5925b9fb4b
            AssignPublicIp: DISABLED
